name: git reset

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: git reset
        run: |
          pwd
          ls -lrt
          git reset HEAD^
          git push -f

